### ISSUE TITLE
Overflows

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-app#26]
- [ ] Campaign tiles (on Home page) overflow on smaller devices
- [x] "Propose a campaign or action" overflows

**Comment by JElgar** [comment]
Ah yeah, let me see if I can get a screenshot!

**Comment by JElgar** [comment]
This is how they should look:

![Screenshot_20210330-213223.png](https://user-images.githubusercontent.com/10330042/113053012-bbb59800-919f-11eb-946a-ab84c97bd382.png)

But sometimes (when 3 lines are required) they look like this:

![Screenshot_20210330-213229.png](https://user-images.githubusercontent.com/10330042/113053105-d25bef00-919f-11eb-9b03-931f864d4a24.png)

**Comment by hailemix** [comment]
ok.

**Comment by hailemix** [comment]
Hi @JElgar, I've updated the code to be expanded and not to be cut like the images before.You can take a look at it.
