### ISSUE TITLE
[BUG] - Back navigation on Android is not closing the app

### ISSUE THREAD

**Issue by kackogut** [now-u/now-u-app#273]
When navigating back on Login or HomeScreen the app is not closed

**To Reproduce**
1. Launch app 
2. Login
3. Navigate back

**Expected behavior**
App is closed

**Comment by JElgar** [comment]
Im guessing this is guilty https://github.com/now-u/now-u-app/blob/main/lib/ui/views/tabs/tabs_view.dart#L87. Presumably we should clear history rather than just blocking popping scope
