### ISSUE TITLE
[BUG] - Time Filter on Actions Page Does Not Display Accurate Filtered Results

### ISSUE THREAD

**Issue by YWKlai** [now-u/now-u-app#319]
**Describe the bug**
When I apply the 'Time' filter on the Action page, I can still see Action results not aligned with the selected times.

**To Reproduce**
1. Go to 'Explore -> Actions tab'
2. Click on 'Time' filter
3. Go back to Action result page
4. Can still see Action results not aligned with the selected times

**Expected behavior**
I should only see action results aligned with my selected times.

**Smartphone (please complete the following information):**
 - Device: [Samsung]
 - App Version 2.11 (beta)

**Additional context**
This is the recording: https://drive.google.com/drive/folders/19c7cVGhYIhuhPxTnq-e_zy8mUG6OpLPL

**Comment by JElgar** [comment]
I think this one is a little ticky just because we currently have overlapping time windows. E.g. we have 5-15 and 15-30, so any action with 15 mins time show up in both. (At least that my hunch of what this issue is about). I guess the easy fix there is to update the time windows to just be 5-14?

**Comment by YWKlai** [comment]
Hi James, thanks for the reply!

I list the proposed fix below:
1. Priority: medium (it is existing behavior in production environment and it seems we haven't received relevant user complaints about this issue)
2. Proposal to fix it: update the time window to the be
- 1-5 mins
- 6-15 mins
- 16-30 mins
- 31-60 mins
3. Dependency check: to ensure time windows displayed on FE page are showing the new time windows as well. For example, those time windows displayed in red box should display the new time group.
![Image](https://github.com/user-attachments/assets/95c057b9-72d7-46fd-ba99-ee66ad4136da)
