### ISSUE TITLE
[BUG] - [iOS beta] Infinite loading splash screen

### ISSUE THREAD

**Issue by kackogut** [now-u/now-u-app#330]
**Describe the Bug**
When opening the app in iOS it gets stuck on the loading screen indefinitely so can't open the app. Even when force closing the app still doesn't work

Smartphone (please complete the following information):
Device: [iPhone]

App Version 2.0.8

**Comment by JElgar** [comment]
Im hoping this is fixed since we've addressed https://github.com/orgs/now-u/projects/6/views/2?pane=issue&itemId=81991202
