### ISSUE TITLE
Investigate and Improve Website Loading Issues

### ISSUE THREAD

**Issue by YWKlai** [now-u/now-u-app#333]
**Is your feature request related to a problem? Please describe.**
Based on the report from [PageSpeed Insights](https://pagespeed.web.dev/analysis/https-www-now-u-com/k8f721i962?form_factor=desktop), the now-u website is currently experiencing slow loading issues. (could refer to the discussion [here](https://docs.google.com/document/d/16Y7pB6eulRnPpc4Xjm4XyxhzYcqwEUGOadVQ_FQNVw0/edit?pli=1&disco=AAABVKhPo4s) to gain more backgrounds)

**Describe the solution you'd like**
We'd like to investigate the root causes and make improvements, aiming to reach a score of 90+ on PageSpeed for every website page.

**Comment by clementinelove** [comment]
Hi! I am afraid you assigned the task to the wrong repo. [now-u-app](https://github.com/now-u/now-u-app) is for mobile app, [now-u-web](https://github.com/now-u/now-u-web) is for the website! Feel free to assign me this task

**Comment by YWKlai** [comment]
Hi @clementinelove, thanks for the check. Let me delete this one and re-create the correct one.

**Comment by JElgar** [comment]
Replaced with https://github.com/now-u/now-u-web/issues/52
