### ISSUE TITLE
[BUG] - Causes not loading

### ISSUE THREAD

**Issue by YWKlai** [now-u/now-u-app#334]
**Describe the bug**
Causes not loading

**To Reproduce**
1. Go to the home page
2. Scroll down to Causes
3. I only see a loading circle - none of the causes load (and I also can't see any Causes in the Causes filters on the Explore page)

**Expected behavior**
I would expect the Cause icons to load

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: Android
 - App Version: Beta 2.0.11

**Additional Context**
original info in the slack report-bug channel: https://now-u.slack.com/archives/C026G1GCKQC/p1727532764403119

**Screenshots**
![Image](https://github.com/user-attachments/assets/ef396053-e7d9-4553-9318-4d7c1fb2a43e)

**Comment by JElgar** [comment]
This should now be fixed. Was related to a breaking change when rolling out API pagination. Fixed by https://github.com/now-u/now-u-backend/commit/35bcaea7820624a4e6cea091e8d0d7cdf3cd6533
