### ISSUE TITLE
[BUG] - Deeplink for login not opening app on IOS 13

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-app#72]
**Describe the bug**
When users click on the login link on the app they are directed to the app store rather than opening the app 

**To Reproduce**
1. Open app
2. Fill in login details
3. Click link in email
4. This opens the app store

**Expected behavior**
This should open the app and then login

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iphone
 - OS: iOS 13
 - App Version: 1.0.1

**Additional context**

**Comment by JElgar** [comment]
Likely to still be broken. @daniil-shumko is going to test

**Comment by daniil-shumko** [comment]
Still an issue on iOS 13.6
