### ISSUE TITLE
Add an 'about us' section to the more menu that links to about us page of website

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-app#82]
Description:
**As a:** User of the app
**Currently**: I currently look in the FAQs page to find out more about now-u
**I want:** a menu item that tells me more about now-u directly
**Because:** so I can find out more about now-u more easily

Size: XS

Reporter:
James Elgar 

Trello link:
https://trello.com/c/Y5wYNuvV/57-add-an-about-us-section-to-the-more-menu-that-links-to-about-us-page-of-website

Comments:
quick fix for linked issue
,More personalized that the FAQs section

**Comment by SoutrikDas** [comment]
I have added a `pageTile` that links to the about us webpage like so 
```dart
{
    'profileTile': ProfileTile("About Us",CustomIcons.ic_faq),
    'link': "https://now-u.com/aboutus",
  },
```
But is the `faq` icon ok ? Or should there be some other icon for About Us ?
![](https://i.ibb.co/C7zsWDz/about-us.gif)

**Comment by JElgar** [comment]
Very nice thank you Soutrik! Let's hold this till we get that icon but other than that this is perfect.
